FROM ghcr.io/void-linux/void-glibc-full:latest
# base
ARG S6_OVERLAY_VERSION=3.1.5.0
ENV PHP_VERSION=8.2
ENV NGINX_PATH /etc/nginx
ENV NGINX_CONF ${NGINX_PATH}/nginx.conf
ENV PHP_CONF /etc/php${PHP_VERSION}/php.ini
ENV FPM_CONF /etc/php${PHP_VERSION}/php-fpm.conf
ENV FPM_POOL /etc/php${PHP_VERSION}/php-fpm.d/www.conf

# bludit
ARG BLUDIT_VERSION=3.15.0
ENV BLUDIT_URL=https://github.com/bludit/bludit/archive/refs/tags/${BLUDIT_VERSION}.tar.gz
ENV BLUDIT_CONTENT=/usr/share/nginx/html/bl-content

# install xz nginx and php
RUN xbps-install -Syu && \
	xbps-install -Syu xz bash curl && \
	xbps-install -Syu nginx && \
	xbps-install -Syu php${PHP_VERSION} php${PHP_VERSION}-fpm php${PHP_VERSION}-gd

# add http user to run nginx and php
RUN useradd -M http

# php config
RUN sed -i -e "s/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/g" ${PHP_CONF} && \
	sed -i -e "s/upload_max_filesize\s*=\s*2M/upload_max_filesize = 100M/g" ${PHP_CONF} && \
	sed -i -e "s/post_max_size\s*=\s*8M/post_max_size = 100M/g" ${PHP_CONF} && \
	sed -i -e "s/variables_order = \"GPCS\"/variables_order = \"EGPCS\"/g" ${PHP_CONF} && \
	sed -i -e "s/;extension=gd/extension=gd/g" ${PHP_CONF}

RUN sed -i -e "s/;daemonize\s*=\s*yes/daemonize = no/g" ${FPM_CONF}

RUN sed -i -e "s/listen = 127.0.0.1:9000/listen = \/var\/run\/php\/php-fpm.sock/g" ${FPM_POOL} && \
	sed -i -e "s/;listen.owner = http/listen.owner = http/g" ${FPM_POOL} && \
	sed -i -e "s/;listen.group = http/listen.group = http/g" ${FPM_POOL} && \
	sed -i -e "s/;listen.mode = 0660/listen.mode = 0660/g" ${FPM_POOL}

# nginx config
RUN mkdir ${NGINX_PATH}/conf.d
COPY conf/default.conf ${NGINX_PATH}/conf.d/default.conf
COPY conf/nginx.conf ${NGINX_CONF}
RUN chown -R http:http /usr/share/nginx/html && \
	chown -R http:http /var/log/nginx && \
	touch /var/log/php-fpm.log && \
	chown http:http /var/log/php-fpm.log && \
	mkdir -p /var/run/php && \
	chown -R http:http /var/run/php

# bludit installation
WORKDIR /tmp
RUN curl -L -o /tmp/bludit.tar.gz ${BLUDIT_URL} && \
	tar xf /tmp/bludit.tar.gz && \
	rm -rf /usr/share/nginx/html && \
	cp -r bludit-* /usr/share/nginx/html && \
	chown -R http:http /usr/share/nginx/html && \
	chmod 755 ${BLUDIT_CONTENT} && \
	sed -i "s/'DEBUG_MODE', FALSE/'DEBUG_MODE', TRUE/g" /usr/share/nginx/html/bl-kernel/boot/init.php && \
	rm -f /tmp/bludit.tar.gz 

# enable services
RUN mkdir -p /etc/s6-overlay/s6-rc.d/nginx/dependencies.d && \
	touch /etc/s6-overlay/s6-rc.d/nginx/dependencies.d/base && \
	touch /etc/s6-overlay/s6-rc.d/nginx/dependencies.d/php-fpm && \
	mkdir -p /etc/s6-overlay/s6-rc.d/php-fpm/dependencies.d && \
	touch /etc/s6-overlay/s6-rc.d/php-fpm/dependencies.d/base && \
	mkdir -p /etc/s6-overlay/s6-rc.d/user/contents.d && \
	touch /etc/s6-overlay/s6-rc.d/user/contents.d/nginx && \
	touch /etc/s6-overlay/s6-rc.d/user/contents.d/php-fpm

COPY s6-rc.d/nginx/run /etc/s6-overlay/s6-rc.d/nginx/run
COPY s6-rc.d/nginx/type /etc/s6-overlay/s6-rc.d/nginx/type
COPY s6-rc.d/php-fpm/run /etc/s6-overlay/s6-rc.d/php-fpm/run
COPY s6-rc.d/php-fpm/type /etc/s6-overlay/s6-rc.d/php-fpm/type

RUN chmod +x /etc/s6-overlay/s6-rc.d/nginx/run && \
	chmod +x /etc/s6-overlay/s6-rc.d/php-fpm/run

# expose nginx
EXPOSE 80

# clean xbps cache
RUN rm -rf /var/cache/xbps/*

# s6-overlay
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz
COPY docker-entrypoint-s6.sh /
ENTRYPOINT ["/docker-entrypoint-s6.sh"]
